window.LOOP = window.LOOP || {};

LOOP.brand = {
  name: "Loop",
  wordmark: "LOOP",
  house: "Loop Trips",
  collection: "Spice Route Luxe",
  tagline: "Bharat at the heart of every journey.",
  logoMark: "Bharat first · World beyond",
  logo: "img/logo.png",
  logoAlt: "Loop Trips — Bharat first, world beyond",
  phone: "+91 99511 39299",
  phoneTel: "+919951139299",
  whatsapp: "+91 99511 39299",
  whatsappLink: "https://wa.me/919951139299",
  email: "concierge@looptrips.com",
  city: "Hyderabad",
  address: "Hitech City, Madhapur",
  addressFull: "Hitech City, Madhapur, Hyderabad, Telangana 500081",
  hours: "10:00–18:00 IST",
  years: "",
  tripsBooked: "",
  rating: "",
  ratingLabel: "",
  license: "",
  iata: "",
  instagram: "https://instagram.com/LOOPTRIPS.IN",
  instagramHandle: "@LOOPTRIPS.IN",
};

LOOP.trust = {
  /* Leave rating blank until Google / WhatsApp reviews are verified. */
  rating: "",
  /* Soft proof only — no invented trip counts. */
  tripsBooked: "India & beyond",
  tripsLabel: "Private weeks planned",
  label: "Private trips · India first",
  licenseNote: "Hyderabad desk · Hitech City",
  /* Extra home-proof span (optional). */
  iataNote: "Private weeks · India & beyond",
};

/* Real team bios: Admin → Brand. Empty until real names/photos are ready. */
LOOP.team = [];

LOOP.reviews = [
  {
    name: "Priya & Arjun",
    place: "Rajasthan · Forts & Palaces",
    rating: 5,
    text: "Every fort stop felt paced, not rushed. The from-price on the site matched what we paid. WhatsApp replies came within the hour.",
    photo: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80",
  },
  {
    name: "Sneha K.",
    place: "Community · Coorg table",
    rating: 5,
    text: "I booked a solo seat and never felt alone at dinner. Small circle, real conversations. Will do Meghalaya next.",
    photo: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=80",
  },
  {
    name: "Rahul Mehta",
    place: "Ladakh · High Road",
    rating: 5,
    text: "Acclimatisation was taken seriously. Pangong sunrise was worth every rupee. Clear cancellation terms before we paid the hold.",
    photo: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=900&q=80",
  },
  {
    name: "Divya Nair",
    place: "Kerala · Backwaters",
    rating: 4,
    text: "Houseboat and spice garden day were exactly as written on the trip page. The Hyderabad desk answered quickly when I needed a change.",
    photo: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80",
  },
];

LOOP.gallery = [
  { src: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80", caption: "Jaipur courtyard · Forts & Palaces" },
  { src: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80", caption: "Leh dawn · High Road" },
  { src: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80", caption: "Backwater light · Kerala" },
  { src: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80", caption: "Coffee estate · Coorg" },
  { src: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80", caption: "Gokarna shore · Solo" },
  { src: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80", caption: "Meghalaya ridge · Community" },
  { src: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80", caption: "Kashi evening · Sanatan" },
  { src: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80", caption: "Maldives villa · World" },
];

const U = (id, w = 1800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

const STAYS = [
  "Five-star and boutique residences, privately selected",
  "Daily breakfast, and dinners where they matter",
  "Private airport and intercity transfers",
  "A dedicated journey designer, 24 hours",
  "All listed experiences, tickets, and guides",
];

const STAYS_IN = [
  "Stays chosen for the hour they keep, not the photograph",
  "Private transfers throughout",
  "A journey designer on Indian hours",
  "Daily breakfast, and the meals named in the plan",
  "All listed rites, tickets, and guides",
];

const STAYS_BIKE = [
  "A serviced motorcycle, or yours in the convoy",
  "Support vehicle, mechanic, and spare parts",
  "Stays that understand dust and early starts",
  "Fuel, permits, and a road captain",
  "Daily breakfast",
];

LOOP.journeys = [
  {
    id: "polska-passion",
    title: "Polska Passion",
    country: "Poland",
    locations: ["Warsaw", "Krakow", "Wrocław", "Poznań", "Gdańsk"],
    duration: "11 Days · 10 Nights",
    days: 11,
    nights: 10,
    pax: 2,
    price: 185000,
    region: "Europe",
    theme: "Heritage",
    status: "Open",
    image: U("photo-1467269204594-9661b134dd2b"),
    gallery: [U("photo-1502602898657-3e91760cbb34"), U("photo-1523906834658-6e24ef2386f9"), U("photo-1467269204594-9661b134dd2b")],
    blurb: "Five Polish cities. One unhurried procession through palaces, amber, and river light.",
    story: "Poland is not a checklist. It is a sequence of rooms — a reconstructed old town, a salt cathedral, a Baltic quay at dusk. We keep the pace human, the hotels historic, and the evenings long.",
    highlights: ["Private Chopin recital in Warsaw", "Wieliczka salt mine after hours", "Vistula river supper in Kraków", "Gdańsk amber atelier visit"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Warsaw", text: "The reconstructed Royal Route, Łazienki Park at first light, and a private piano hour." },
      { day: "04–06", title: "Kraków", text: "Wawel at opening, Kazimierz without the crowds, Wieliczka in silence." },
      { day: "07–08", title: "Wrocław & Poznań", text: "Dwarf-hunting, market squares, and a slow train between gothic towns." },
      { day: "09–11", title: "Gdańsk", text: "The Motława, shipyards of memory, and the Baltic as a last chapter." },
    ],
    bestTime: "May – September",
  },
  {
    id: "atlantic-pearl",
    title: "The Atlantic Pearl",
    country: "Portugal",
    locations: ["Lisbon", "Douro", "Algarve", "Porto"],
    duration: "10 Days · 9 Nights",
    days: 10,
    nights: 9,
    pax: 2,
    price: 420000,
    region: "Europe",
    theme: "Coast",
    status: "Limited",
    featured: true,
    image: U("photo-1555881400-74d7acaacd8b"),
    gallery: [U("photo-1555881400-74d7acaacd8b"), U("photo-1526392060635-9d6019884377"), U("photo-1483729558449-99ef09a8c325")],
    blurb: "Lisbon’s hills, the Douro’s terraces, and the Algarve’s cliffs — Portugal at its most considered.",
    story: "This is Portugal as a piece of jewellery: gold light, azulejo, and wine that tastes of schist. We stay in palácios and quintas. We do not rush the Atlantic.",
    highlights: ["Private fado in Alfama", "Quinta lunch above the Douro", "Algarve cliff walk at golden hour", "Port tasting in a Gaia lodge"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Lisbon", text: "Tramless mornings in Alfama, Belém without the queue, a tiled courtyard supper." },
      { day: "04–06", title: "Douro", text: "A quinta terrace, a river boat at dusk, vineyards that fall into water." },
      { day: "07–08", title: "Algarve", text: "Cliffs, coves, and a table on the sand." },
      { day: "09–10", title: "Porto", text: "The Ribeira, a lodge in Vila Nova de Gaia, and one last glass." },
    ],
    bestTime: "April – October",
  },
  {
    id: "cape-of-good-hope",
    title: "Cape of Good Hope",
    country: "South Africa",
    locations: ["Cape Town", "Johannesburg", "Sun City", "Knysna", "Southern Kruger"],
    duration: "10 Days · 9 Nights",
    days: 10,
    nights: 9,
    pax: 2,
    price: 320000,
    region: "Africa",
    theme: "Safari",
    status: "Open",
    featured: true,
    image: U("photo-1580060839134-75a5edca2e99"),
    gallery: [U("photo-1516426122078-c23e76319801"), U("photo-1516426122078-c23e76319801"), U("photo-1547471080-7cc2caa01a7e")],
    blurb: "Table Mountain, the Garden Route, and Kruger at first light — the southern tip, fully drawn.",
    story: "South Africa asks for range: city, coast, bush. We give each its proper weight. Wine on the slopes of Stellenbosch. Silence in the Kruger dawn.",
    highlights: ["Table Mountain by private cable", "Stellenbosch cellar lunch", "Knysna lagoon cruise", "Two game drives daily in Kruger"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Cape Town", text: "The mountain, the peninsula, and Constantia in the afternoon." },
      { day: "04–05", title: "Knysna", text: "The Garden Route, lagoon light, and forest air." },
      { day: "06", title: "Johannesburg & Sun City", text: "A pause in gold country, then the Pilanesberg edge." },
      { day: "07–10", title: "Southern Kruger", text: "Dawn drives, a hide at the waterhole, stars without a city." },
    ],
    bestTime: "May – September",
  },
  {
    id: "himalayan-expedition",
    title: "The Himalayan Expedition",
    country: "Ladakh",
    locations: ["Leh", "Nubra", "Pangong"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 72000,
    region: "India",
    theme: "Mountains",
    status: "Open",
    image: U("photo-1626621341517-bbf3d9990a23"),
    gallery: [U("photo-1506905925346-21bda4d32df4"), U("photo-1581793745862-99fde7fa73d2"), U("photo-1544735716-392fe2489ffa")],
    blurb: "High desert, monasteries, and a lake the colour of a held breath.",
    story: "Ladakh is altitude as a teacher. We acclimatise properly. We sleep in camps that do not pretend to be hotels. Pangong is earned.",
    highlights: ["Hemis and Thiksey at opening", "Khardung La crossing", "Nubra dune hour", "Pangong sunrise"],
    inclusions: ["Boutique stays and luxury camps", "Oxygen support and acclimatisation protocol", "Private vehicle throughout", "All inner-line permits", "Daily breakfast and selected meals"],
    itinerary: [
      { day: "01–02", title: "Leh", text: "Rest, tea, and the Indus. No heroics on day one." },
      { day: "03–04", title: "Nubra", text: "The high pass, the dunes, a double-humped stillness." },
      { day: "05–06", title: "Pangong", text: "Blue that does not exist elsewhere. A night by the water." },
      { day: "07", title: "Return", text: "Down to Leh. The sky still in the lungs." },
    ],
    bestTime: "June – September",
  },
  {
    id: "historical-egypt",
    title: "Historical Egypt",
    country: "Egypt",
    locations: ["Cairo", "Siwa Oasis", "Luxor", "Aswan", "Alexandria"],
    duration: "14 Days · 13 Nights",
    days: 14,
    nights: 13,
    pax: 2,
    price: 165000,
    region: "Africa",
    theme: "Heritage",
    status: "Open",
    image: U("photo-1572252009286-268acec5ca0a"),
    gallery: [U("photo-1591604129939-f1efa4d9f7fa"), U("photo-1587595431973-160d0d94add1"), U("photo-1548013146-72479768bada")],
    blurb: "Pharaohs, an oasis, and the Nile — Egypt as a long, luminous sentence.",
    story: "Fourteen days so that Cairo is not a blur and Siwa is not a postcard. Private guides who speak in stories, not scripts. A dahabiya where a cruise would be too loud.",
    highlights: ["Giza at opening, no circus", "Siwa salt lakes and oracle", "Luxor after dark", "Nile sailing Aswan to Luxor"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Cairo", text: "The Museum, Islamic Cairo, and the pyramids before the coaches." },
      { day: "04–06", title: "Siwa", text: "An oasis at the edge of the Western Desert. Silence as a luxury." },
      { day: "07–10", title: "Luxor & Aswan", text: "Karnak, the Valley, a slow river, Philae at dusk." },
      { day: "11–14", title: "Alexandria", text: "The Mediterranean again. Libraries, sea light, a last seafood supper." },
    ],
    bestTime: "October – April",
  },
  {
    id: "ancient-egypt",
    title: "Ancient Egypt",
    country: "Egypt",
    locations: ["Cairo", "Black & White Desert", "Luxor", "Aswan", "Alexandria"],
    duration: "11 Days · 10 Nights",
    days: 11,
    nights: 10,
    pax: 2,
    price: 145000,
    region: "Africa",
    theme: "Heritage",
    status: "Open",
    image: U("photo-1591604129939-f1efa4d9f7fa"),
    gallery: [U("photo-1572252009286-268acec5ca0a"), U("photo-1548013146-72479768bada"), U("photo-1587595431973-160d0d94add1")],
    blurb: "Desert sculptures, temple corridors, and the Nile — a tighter, deeper Egypt.",
    story: "The White Desert looks like a planet that forgot to finish itself. We camp well. Then the river, then stone that has outlasted every empire that tried to own it.",
    highlights: ["White Desert camp under stars", "Giza private access window", "Hot-air dawn over Luxor", "Felucca hour in Aswan"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Cairo & Giza", text: "The capital, then the plateau. Measured, not frantic." },
      { day: "04–05", title: "Black & White Desert", text: "Sculpted chalk, a fire, a sky without a ceiling." },
      { day: "06–09", title: "Luxor & Aswan", text: "Temples in sequence. The river as a road." },
      { day: "10–11", title: "Alexandria", text: "Sea air after stone. A library, a corniche, a close." },
    ],
    bestTime: "October – April",
  },
  {
    id: "durga-pujo",
    title: "Durga Pujo Delight",
    country: "Kolkata",
    locations: ["Kolkata"],
    duration: "6 Days · 5 Nights",
    days: 6,
    nights: 5,
    pax: 2,
    price: 65000,
    region: "India",
    theme: "Culture",
    status: "Seasonal",
    image: U("photo-1570168007204-dfb528c6958f"),
    gallery: [U("photo-1582510003544-4d00b7f74220"), U("photo-1524492412937-b28074a5d7da"), U("photo-1603262110263-fb0112e7cc33")],
    blurb: "The city as a festival. Pandals, adda, and a river that has seen every century.",
    story: "Kolkata at Pujo is not tourism. It is immersion. We give you a local who knows which pandal is art and which is noise, and a table that understands the city’s appetite.",
    highlights: ["Private pandal trail after midnight", "Heritage North Kolkata walk", "Hooghly sunset on a private boat", "Bengali feast with a home cook"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Arrival & adda", text: "Park Street, a club verandah, the city introducing itself." },
      { day: "03–04", title: "Pujo", text: "Pandal hopping with a curator. Dhak, dhunuchi, no maps required." },
      { day: "05–06", title: "The river", text: "Kumartuli, the ghats, a last mishti and a slow goodbye." },
    ],
    bestTime: "September – October",
  },
  {
    id: "beach-paradise-seychelles",
    title: "Beach Paradise",
    country: "Seychelles",
    locations: ["Mahé", "Praslin"],
    duration: "6 Days · 5 Nights",
    days: 6,
    nights: 5,
    pax: 2,
    price: 195000,
    region: "Islands",
    theme: "Coast",
    status: "Open",
    image: U("photo-1500375592092-40eb2168fd21"),
    gallery: [U("photo-1559827260-dc66d52bef19"), U("photo-1514282401047-d79a71a590e8"), U("photo-1476514525535-07fb3b4ae5f1")],
    blurb: "Granite boulders, turquoise that does not need a filter, and time that forgets to pass.",
    story: "A shorter Seychelles for those who want the water more than the itinerary. Two islands. One standard of stillness.",
    highlights: ["Beau Vallon dusk", "Anse Lazio day", "Creole table on the beach", "Island hop by private boat"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Mahé", text: "The main island, Morne Seychellois above you, the reef below." },
      { day: "04–06", title: "Praslin", text: "Vallée de Mai, Anse Lazio, and nothing scheduled after noon." },
    ],
    bestTime: "April – June, September – November",
  },
  {
    id: "tropical-heaven-bali",
    title: "Tropical Heaven",
    country: "Bali",
    locations: ["Ubud", "Uluwatu"],
    duration: "5 Days · 4 Nights",
    days: 5,
    nights: 4,
    pax: 2,
    price: 100000,
    region: "Asia",
    theme: "Wellness",
    status: "Open",
    image: U("photo-1537996194471-e657df975ab4"),
    gallery: [U("photo-1518548419970-58e3b4079ab2"), U("photo-1555400038-63f5ba517a47"), U("photo-1555400038-63f5ba517a47")],
    blurb: "Rice terraces, a cliff temple, and a villa that understands quiet.",
    story: "Five days is enough if nothing is wasted. We skip the souvenir circuit. Ubud for the interior life, Uluwatu for the ocean’s edge.",
    highlights: ["Private blessing in a village temple", "Tegallalang at first light", "Uluwatu kecak without the crush", "Balinese spa in the villa"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Ubud", text: "Jungle, rice, a chef who cooks from the garden." },
      { day: "04–05", title: "Uluwatu", text: "Cliffs, a temple, a last swim into the Indian Ocean." },
    ],
    bestTime: "April – October",
  },
  {
    id: "vintage-voyage",
    title: "Vintage Voyage",
    country: "Europe",
    locations: ["Paris", "Swiss Alps", "Venice", "Vienna"],
    duration: "12 Days · 11 Nights",
    days: 12,
    nights: 11,
    pax: 2,
    price: 380000,
    region: "Europe",
    theme: "Heritage",
    status: "Limited",
    featured: true,
    image: U("photo-1467269204594-9661b134dd2b"),
    gallery: [U("photo-1502602898657-3e91760cbb34"), U("photo-1523906834658-6e24ef2386f9"), U("photo-1516550893923-42d28e5677af")],
    blurb: "Echoes of Europe — grand hotels, slow trains, and cities that invented evenings.",
    story: "A vintage Europe is not nostalgia. It is a standard: the right hotel, the right table, the train that still feels like an arrival. Four cities. No filler.",
    highlights: ["Orient-inspired rail legs", "Private Alpine peak morning", "Venice after the day-trippers", "Vienna with a music historian"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Paris", text: "The Left Bank as a neighbourhood, not a monument list." },
      { day: "04–06", title: "The Alps", text: "A palace hotel, a peak, air that edits the mind." },
      { day: "07–09", title: "Venice", text: "A quiet campo, a private vaporetto, stone and water." },
      { day: "10–12", title: "Vienna", text: "A ring of palaces, a last concert, coffee as ceremony." },
    ],
    bestTime: "April – June, September – October",
  },
  {
    id: "wanderlust-europe",
    title: "Wanderlust Europe",
    country: "Europe",
    locations: ["Amsterdam", "Bruges", "Paris", "Barcelona"],
    duration: "12 Days · 11 Nights",
    days: 12,
    nights: 11,
    pax: 2,
    price: 410000,
    region: "Europe",
    theme: "Cities",
    status: "Open",
    image: U("photo-1476514525535-07fb3b4ae5f1"),
    gallery: [U("photo-1534351590666-13e3e96b5017"), U("photo-1555881400-74d7acaacd8b"), U("photo-1583422409516-2895a77efded")],
    blurb: "Four capitals of appetite — canals, cobbles, light, and a long table.",
    story: "For those who want Europe as a conversation between cities. We travel by train. We stay in houses that belong to their streets.",
    highlights: ["Canal house breakfast", "Bruges after closing", "Paris atelier visit", "Barcelona with a food historian"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Amsterdam", text: "Canals as a compass. A museum without the queue." },
      { day: "04–05", title: "Bruges", text: "A medieval pause. Chocolate, bells, brick." },
      { day: "06–08", title: "Paris", text: "One arrondissement properly, not six poorly." },
      { day: "09–12", title: "Barcelona", text: "Gaudí, the sea, and a last vermouth." },
    ],
    bestTime: "April – October",
  },
  {
    id: "alpine-escape",
    title: "Alpine Escape",
    country: "New Zealand",
    locations: ["Auckland", "Queenstown"],
    duration: "14 Days · 13 Nights",
    days: 14,
    nights: 13,
    pax: 2,
    price: 450000,
    region: "Oceania",
    theme: "Mountains",
    status: "Open",
    featured: true,
    image: U("photo-1464822759023-fed622ff2c3b"),
    gallery: [U("photo-1507699622108-4be3abd695ad"), U("photo-1464822759023-fed622ff2c3b"), U("photo-1506905925346-21bda4d32df4")],
    blurb: "Two islands, one standard of landscape. Fiords, vineyards, and light that feels unused.",
    story: "New Zealand rewards time. Fourteen days so the South Island is not a fly-by. Helicopters where roads would steal the day. Lodges that face the water.",
    highlights: ["Milford by helicopter", "Wanaka silent morning", "Central Otago cellar door", "Auckland harbour dusk"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Auckland", text: "The harbour, Waiheke, a city that faces the Pacific." },
      { day: "04–14", title: "Queenstown & the South", text: "Lakes, alps, a fiord, and lodges that understand weather." },
    ],
    bestTime: "December – March",
  },
  {
    id: "kenya-unveiled",
    title: "Kenya Unveiled",
    country: "Kenya",
    locations: ["Nairobi", "Laikipia", "Masai Mara"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 2,
    price: 280000,
    region: "Africa",
    theme: "Safari",
    status: "Open",
    image: U("photo-1516426122078-c23e76319801"),
    gallery: [U("photo-1516426122078-c23e76319801"), U("photo-1547471080-7cc2caa01a7e"), U("photo-1516026672322-bc52d61a55d5")],
    blurb: "Highlands, conservancy, and the Mara — Kenya without the conveyor belt.",
    story: "We skip the crowded circuits. Laikipia for space. The Mara for the theatre of grass and sky. Camps that disappear in the morning.",
    highlights: ["Conservancy night drive", "Walking safari with a guide", "Mara balloon at dawn", "Sundowner on the escarpment"],
    inclusions: STAYS,
    itinerary: [
      { day: "01", title: "Nairobi", text: "A city pause. Giraffe Manor grounds, or a gallery, then north." },
      { day: "02–04", title: "Laikipia", text: "A private conservancy. Walking, riding, stars." },
      { day: "05–08", title: "Masai Mara", text: "The grass ocean. Two drives a day. Nothing else required." },
    ],
    bestTime: "July – October",
  },
  {
    id: "timeless-england",
    title: "Timeless England",
    country: "England",
    locations: ["London"],
    duration: "10 Days · 9 Nights",
    days: 10,
    nights: 9,
    pax: 2,
    price: 245000,
    region: "Europe",
    theme: "Cities",
    status: "Open",
    image: U("photo-1513635269975-59663e0ac1ad"),
    gallery: [U("photo-1486299267070-83823f5448dd"), U("photo-1520986606214-8b456906c813"), U("photo-1513635269975-59663e0ac1ad")],
    blurb: "London as a residence, not a visit. Clubs, gardens, and the river as a spine.",
    story: "Ten nights in one city is a luxury. You learn which park is yours. We arrange a house hotel, a table at the right hour, and a countryside day that is not a coach tour.",
    highlights: ["Private National Gallery hour", "Thames at blue hour", "A day in the Cotswolds", "Members-club supper"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–07", title: "London", text: "Neighbourhoods, not landmarks. A tailor, a garden, a concert." },
      { day: "08–09", title: "The countryside", text: "Stone villages, a long lunch, back before dark." },
      { day: "10", title: "A last morning", text: "The river. A bookstore. The airport when you are ready." },
    ],
    bestTime: "May – September",
  },
  {
    id: "scandinavian-serenity",
    title: "Scandinavian Serenity",
    country: "Nordics",
    locations: ["Norway", "Sweden", "Denmark", "Finland"],
    duration: "14 Days · 13 Nights",
    days: 14,
    nights: 13,
    pax: 2,
    price: 390000,
    region: "Europe",
    theme: "Design",
    status: "Open",
    image: U("photo-1509356843151-3e7d96241e11"),
    gallery: [U("photo-1531366936337-7c912a4589a7"), U("photo-1509356843151-3e7d96241e11"), U("photo-1531366936337-7c912a4589a7")],
    blurb: "Fjords, design, sauna, and light that behaves like a season of its own.",
    story: "Four countries, one temperament: restraint as warmth. We travel by rail and water. We stay where the architecture is the souvenir.",
    highlights: ["Norwegian fjord sailing", "Stockholm archipelago lunch", "Copenhagen design walk", "Finnish lakeside sauna"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–04", title: "Norway", text: "Oslo, then a fjord. Water as architecture." },
      { day: "05–07", title: "Sweden", text: "Stockholm’s islands, a fika that lasts." },
      { day: "08–10", title: "Denmark", text: "Copenhagen’s tables and quiet courtyards." },
      { day: "11–14", title: "Finland", text: "Forest, sauna, a lake that holds the sky." },
    ],
    bestTime: "June – August",
  },
  {
    id: "singapore-malaysia",
    title: "Singapore & Malaysia",
    country: "Singapore & Malaysia",
    locations: ["Singapore", "Sentosa", "Kuala Lumpur", "Penang", "Langkawi"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 135000,
    region: "Asia",
    theme: "Cities",
    status: "Open",
    image: U("photo-1525625293386-3f8f99389edd"),
    gallery: [U("photo-1525625293386-3f8f99389edd"), U("photo-1590077428593-a55bb07c4665"), U("photo-1590077428593-a55bb07c4665")],
    blurb: "Two countries, five textures — skyline, spice, island, and rain trees.",
    story: "A week that tastes of laksa and looks like the future. Singapore for precision. Malaysia for soul. Langkawi to exhale.",
    highlights: ["Gardens by the Bay at night", "George Town street-food trail", "Petronas twilight", "Langkawi mangrove dusk"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Singapore & Sentosa", text: "The city-state, then an island pause." },
      { day: "03–04", title: "Kuala Lumpur", text: "Towers, temples, a night market with a local." },
      { day: "05", title: "Penang", text: "George Town’s shophouses and a proper hawker supper." },
      { day: "06–07", title: "Langkawi", text: "The Andaman. Nothing required after breakfast." },
    ],
    bestTime: "December – March",
  },
  {
    id: "tropical-island-singapore",
    title: "Tropical Island Retreat",
    country: "Singapore",
    locations: ["Singapore", "Sentosa"],
    duration: "4 Days · 3 Nights",
    days: 4,
    nights: 3,
    pax: 2,
    price: 118000,
    region: "Asia",
    theme: "Coast",
    status: "Open",
    image: U("photo-1525625293386-3f8f99389edd"),
    gallery: [U("photo-1525625293386-3f8f99389edd"), U("photo-1493976040374-85c8e12f0c0e"), U("photo-1493976040374-85c8e12f0c0e")],
    blurb: "A long weekend in the city of gardens — and an island that pretends it is elsewhere.",
    story: "Four days, no waste. A suite that faces the water. A table that understands the city’s appetite. Sentosa when the skyline is enough.",
    highlights: ["Marina Bay dawn", "Private hawker tasting", "Sentosa spa afternoon", "Night safari or gardens"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Singapore", text: "The bay, the gardens, a neighbourhood supper." },
      { day: "03–04", title: "Sentosa", text: "Beach, spa, a last swim before the flight." },
    ],
    bestTime: "Year-round",
  },
  {
    id: "magical-montenegro",
    title: "Magical Montenegro",
    country: "Montenegro",
    locations: ["Podgorica", "Budva", "Kotor"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 165000,
    region: "Europe",
    theme: "Coast",
    status: "Open",
    image: U("photo-1555990793-da11153b2473"),
    gallery: [U("photo-1507525428034-b723cf961d3e"), U("photo-1613395877344-13d4a8e0d49e"), U("photo-1476514525535-07fb3b4ae5f1")],
    blurb: "A fjord that is a bay, stone towns, and a coast that still has rooms to breathe.",
    story: "Montenegro is the Adriatic before it became a formula. Kotor’s walls at opening. Budva when the yachts are elsewhere. A mountain road for one afternoon.",
    highlights: ["Kotor walls at sunrise", "Private bay cruise", "Lovćen mountain hour", "Konoba supper on the water"],
    inclusions: STAYS,
    itinerary: [
      { day: "01", title: "Podgorica", text: "Arrival, then south toward the water." },
      { day: "02–04", title: "Kotor", text: "The bay. A fortress. Evenings that last." },
      { day: "05–07", title: "Budva", text: "The old town, a beach, a last swim in the Adriatic." },
    ],
    bestTime: "May – September",
  },
  {
    id: "voyage-south-korea",
    title: "Voyage South Korea",
    country: "South Korea",
    locations: ["Seoul", "Busan", "Gyeongju"],
    duration: "11 Days · 10 Nights",
    days: 11,
    nights: 10,
    pax: 2,
    price: 210000,
    region: "Asia",
    theme: "Culture",
    status: "Open",
    image: U("photo-1546874177-9e664107314e"),
    gallery: [U("photo-1540959733332-eab4deabeeaf"), U("photo-1540959733332-eab4deabeeaf"), U("photo-1514565131-fce0801e5785")],
    blurb: "Palaces, markets, and a coastline that faces Japan — Korea at a human pace.",
    story: "Eleven days so Seoul is not only neon. A hanok night. A temple breakfast. Busan for the sea. Gyeongju for the kings who still sleep in the grass.",
    highlights: ["Hanok stay in Jeonju or Seoul", "Private palace after hours", "Busan coastal rail", "Gyeongju at dusk"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–05", title: "Seoul", text: "Palaces, alleys, a table that requires a reservation months ahead." },
      { day: "06–08", title: "Gyeongju", text: "Tumuli parks, a temple in the forest." },
      { day: "09–11", title: "Busan", text: "The sea, a market, a last soju with a view." },
    ],
    bestTime: "April – June, September – November",
  },
  {
    id: "gorgeous-greece",
    title: "Gorgeous Greece",
    country: "Greece",
    locations: ["Athens", "Mykonos", "Santorini"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 195000,
    region: "Europe",
    theme: "Coast",
    status: "Open",
    image: U("photo-1613395877344-13d4a8e0d49e"),
    gallery: [U("photo-1613395877344-13d4a8e0d49e"), U("photo-1570077188670-e3a8d69ac5ff"), U("photo-1570077188670-e3a8d69ac5ff")],
    blurb: "Marble, whitewash, and a caldera that performs every evening.",
    story: "Greece as a trio: the capital’s stone, Mykonos when it is still a village at dawn, Santorini from a cave suite that faces the volcano.",
    highlights: ["Acropolis at opening", "Private Cycladic boat day", "Oia without the sunset scrum", "Athens tavern as the locals use it"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Athens", text: "The Acropolis, a neighbourhood, a table in Plaka that is not a trap." },
      { day: "03–04", title: "Mykonos", text: "Windmills, a beach that is still a beach, not a club." },
      { day: "05–07", title: "Santorini", text: "The caldera. A cave. Light as a material." },
    ],
    bestTime: "May – June, September – October",
  },
  {
    id: "swiss-essence",
    title: "Swiss Essence",
    country: "Switzerland",
    locations: ["Zürich", "Lucerne", "Interlaken", "Zermatt"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 2,
    price: 285000,
    region: "Europe",
    theme: "Mountains",
    status: "Open",
    image: U("photo-1530122037265-a5f1f91d3b99"),
    gallery: [U("photo-1506905925346-21bda4d32df4"), U("photo-1506905925346-21bda4d32df4"), U("photo-1464822759023-fed622ff2c3b")],
    blurb: "Lakes, peaks, and trains that arrive as a form of courtesy.",
    story: "Switzerland is precision applied to landscape. We ride the trains that deserve it. We sleep where the Matterhorn is a neighbour, not a postcard.",
    highlights: ["Lucerne lake steamer", "Jungfrau region morning", "Gornergrat to the Matterhorn", "Zürich old town supper"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Zürich & Lucerne", text: "The lake cities. Clean light, quiet luxury." },
      { day: "03–05", title: "Interlaken", text: "Two lakes, a valley, a peak if the weather agrees." },
      { day: "06–08", title: "Zermatt", text: "Car-free, glacier-close, a last fondue that is not a joke." },
    ],
    bestTime: "June – September",
  },
  {
    id: "turkey",
    title: "Turkey",
    country: "Turkey",
    locations: ["Istanbul", "Cappadocia", "Bodrum"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 2,
    price: 148000,
    region: "Europe",
    theme: "Heritage",
    status: "Open",
    image: U("photo-1541432901042-2d8bd64b4a9b"),
    gallery: [U("photo-1541432901042-2d8bd64b4a9b"), U("photo-1527838832700-5059252407fa"), U("photo-1641128324972-af3212f0f6bd")],
    blurb: "A city on two continents, a valley of chimneys, and an Aegean close.",
    story: "Turkey is a hinge. We give Istanbul the days it deserves, Cappadocia a dawn that is earned, Bodrum a coastline that still knows how to be lazy.",
    highlights: ["Bosphorus private boat", "Sunrise balloons over Göreme", "Cave hotel night", "Bodrum peninsula supper"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Istanbul", text: "The old city, a hamam, a table in Karaköy." },
      { day: "04–06", title: "Cappadocia", text: "Valleys, balloons, a cave that is a suite." },
      { day: "07–08", title: "Bodrum", text: "The Aegean. White houses. A last swim." },
    ],
    bestTime: "April – June, September – October",
  },
  {
    id: "jewel-of-iberia",
    title: "Jewel of Iberia",
    country: "Spain",
    locations: ["Barcelona", "Valencia", "Ibiza", "Granada", "Seville", "Madrid"],
    duration: "14 Days · 13 Nights",
    days: 14,
    nights: 13,
    pax: 2,
    price: 310000,
    region: "Europe",
    theme: "Heritage",
    status: "Open",
    featured: true,
    image: U("photo-1539037116277-4db20889f2d4"),
    gallery: [U("photo-1558642452-9d2a7deb7f62"), U("photo-1583422409516-2895a77efded"), U("photo-1555881400-74d7acaacd8b")],
    blurb: "Six Spanish movements — Gaudí, rice, island, Alhambra, flamenco, and the capital.",
    story: "Spain is too large for a weekend. Fourteen days so Andalusia is not a blur and Ibiza is not only a night. We eat where the cooks still have grandmothers.",
    highlights: ["Alhambra at first entry", "Private flamenco in Seville", "Valencia paella at source", "Ibiza countryside, not the club"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Barcelona", text: "The Eixample, a Gaudí interior, the sea." },
      { day: "04–05", title: "Valencia", text: "Light, rice, a city that invented the afternoon." },
      { day: "06–07", title: "Ibiza", text: "Pine, salt, a table in the hills." },
      { day: "08–14", title: "Andalusia & Madrid", text: "Granada, Seville, then the capital as a last act." },
    ],
    bestTime: "April – June, September – October",
  },
  {
    id: "dreamy-maldives",
    title: "Dreamy Island",
    country: "Maldives",
    locations: ["Noonu Atoll", "Dhaalu Atoll"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 245000,
    region: "Islands",
    theme: "Coast",
    status: "Limited",
    featured: true,
    image: U("photo-1514282401047-d79a71a590e8"),
    gallery: [U("photo-1514282401047-d79a71a590e8"), U("photo-1439066615861-d1af74d74000"), U("photo-1507525428034-b723cf961d3e")],
    blurb: "Two atolls. Overwater quiet. The Indian Ocean as a private room.",
    story: "The Maldives is simple if you choose well. We split the week: one house reef, one quieter atoll. No entertainment schedule. The lagoon is the programme.",
    highlights: ["Seaplane arrival", "Sunset dolphin cruise", "Overwater spa", "Private sandbank supper"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–04", title: "Noonu Atoll", text: "A house reef. A villa. Time without a clock." },
      { day: "05–07", title: "Dhaalu Atoll", text: "A second palette of blue. A last night on the water." },
    ],
    bestTime: "December – April",
  },
  {
    id: "island-of-rainbows",
    title: "Island of Rainbows",
    country: "Mauritius",
    locations: ["Port Louis"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 175000,
    region: "Islands",
    theme: "Coast",
    status: "Open",
    image: U("photo-1586861635167-e5223aadc9fe"),
    gallery: [U("photo-1507525428034-b723cf961d3e"), U("photo-1559827260-dc66d52bef19"), U("photo-1476514525535-07fb3b4ae5f1")],
    blurb: "A volcanic island that learned how to be gentle — lagoons, rum, and a mountain in the mist.",
    story: "Mauritius is not a beach with a name. It is a culture of tables, a peak called Pieter Both, and water that holds every colour at once.",
    highlights: ["Le Morne at dawn", "Private catamaran along the west", "Port Louis market with a cook", "Rum estate afternoon"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "The west", text: "Le Morne, a lagoon, a resort that faces Africa." },
      { day: "04–05", title: "Port Louis & the north", text: "The capital, a garden, a table inland." },
      { day: "06–07", title: "The south", text: "Wilder coast, a last waterfall, the airport when the week is done." },
    ],
    bestTime: "May – December",
  },
  {
    id: "kingdom-of-happiness",
    title: "Kingdom of Happiness",
    country: "Bhutan",
    locations: ["Thimphu", "Punakha", "Paro"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 155000,
    region: "Asia",
    theme: "Mountains",
    status: "Open",
    image: U("photo-1602216056096-3b40cc0c9944"),
    gallery: [U("photo-1544735716-392fe2489ffa"), U("photo-1506905925346-21bda4d32df4"), U("photo-1581793745862-99fde7fa73d2")],
    blurb: "A last Himalayan kingdom. Dzongs, a valley, and a monastery on a cliff.",
    story: "Bhutan rations visitors for a reason. We honour the pace: temples in the morning, valleys in the afternoon, Tiger’s Nest when the legs are ready.",
    highlights: ["Tiger’s Nest with a private guide", "Punakha Dzong at river light", "Thimphu craft morning", "Farmhouse supper"],
    inclusions: ["Licensed Bhutanese guide and vehicle", "Sustainable development fee handled", "Boutique lodges", "All meals", "Monument permits"],
    itinerary: [
      { day: "01–02", title: "Paro & Thimphu", text: "The valley of arrival, then the capital’s quiet order." },
      { day: "03–04", title: "Punakha", text: "A dzong between rivers. A walk through mustard fields." },
      { day: "05–07", title: "Paro", text: "The cliff monastery. A last butter tea. The flight down." },
    ],
    bestTime: "March – May, September – November",
  },
  {
    id: "million-elephants",
    title: "Kingdom of a Million Elephants",
    country: "Laos",
    locations: ["Luang Prabang", "Vientiane", "Pakse"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 125000,
    region: "Asia",
    theme: "Heritage",
    status: "Open",
    image: U("photo-1559592413-7cec4d0cae2b"),
    gallery: [U("photo-1552465011-b4e21bf6e79a"), U("photo-1552465011-b4e21bf6e79a"), U("photo-1493976040374-85c8e12f0c0e")],
    blurb: "Mekong dawns, French-Lao verandahs, and waterfalls in the south.",
    story: "Laos still allows a slower century. Luang Prabang for the alms and the river. Vientiane for a capital that has not shouted. Pakse for the falls.",
    highlights: ["Tak Bat at first light", "Kuang Si without the midday crowd", "Mekong slow boat hour", "4000 Islands pause"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Luang Prabang", text: "Temples, the confluence, a night market that is still a market." },
      { day: "04–05", title: "Vientiane", text: "The capital’s river, a patisserie, a temple at dusk." },
      { day: "06–07", title: "Pakse", text: "The Bolaven, water on stone, a last Mekong evening." },
    ],
    bestTime: "November – February",
  },
  {
    id: "jewel-of-the-desert",
    title: "The Jewel of the Desert",
    country: "Dubai",
    locations: ["Dubai"],
    duration: "5 Days · 4 Nights",
    days: 5,
    nights: 4,
    pax: 2,
    price: 128000,
    region: "Middle East",
    theme: "Cities",
    status: "Open",
    image: U("photo-1512453979798-5ea266f8880c"),
    gallery: [U("photo-1518684079-3c830dcef090"), U("photo-1582672060674-bc2bd808a8b5"), U("photo-1546412414-e1885259563a")],
    blurb: "A city invented from sand and will — towers, desert, and a creek that remembers dhows.",
    story: "Five nights is the right length. A hotel that is a statement. A desert that is not a theme park. Old Dubai before the skyline, then the skyline as theatre.",
    highlights: ["Private desert evening", "Alserkal or creek dhow dusk", "Burj at golden hour", "Emirati tasting table"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "The creek & the old", text: "Abra, spice, a neighbourhood that predates the towers." },
      { day: "03", title: "The desert", text: "Dunes, a table, stars that the city almost hid." },
      { day: "04–05", title: "The new", text: "The waterfront, a last spa, a flight that feels too soon." },
    ],
    bestTime: "November – March",
  },
  {
    id: "oceans-hidden-treasure",
    title: "Ocean’s Hidden Treasure",
    country: "Seychelles",
    locations: ["Mahé", "Praslin", "La Digue"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 255000,
    region: "Islands",
    theme: "Coast",
    status: "Open",
    image: U("photo-1514282401047-d79a71a590e8"),
    gallery: [U("photo-1500375592092-40eb2168fd21"), U("photo-1559827260-dc66d52bef19"), U("photo-1514282401047-d79a71a590e8")],
    blurb: "Three islands, granite cathedrals, and bicycles on La Digue.",
    story: "The fuller Seychelles. Mahé for the mountain, Praslin for the coco de mer, La Digue for a pace that still uses two wheels.",
    highlights: ["Anse Source d’Argent", "Vallée de Mai", "Private inter-island hops", "Creole kitchen supper"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Mahé", text: "The spine of the archipelago. A beach, a peak." },
      { day: "03–04", title: "Praslin", text: "The garden of Eden, if you believe the French." },
      { day: "05–07", title: "La Digue", text: "Boulders, bicycles, a last lagoon." },
    ],
    bestTime: "April – June, September – November",
  },
  {
    id: "eighth-continent",
    title: "The Eighth Continent",
    country: "Madagascar",
    locations: ["Antananarivo", "Andasibe", "Nosy Be"],
    duration: "7 Days · 7 Nights",
    days: 7,
    nights: 7,
    pax: 2,
    price: 185000,
    region: "Africa",
    theme: "Safari",
    status: "Open",
    image: U("photo-1547471080-7cc2caa01a7e"),
    gallery: [U("photo-1516426122078-c23e76319801"), U("photo-1489392191049-fc10c97e64b6"), U("photo-1507525428034-b723cf961d3e")],
    blurb: "Lemurs at dawn, baobabs if the road allows, and an island that is its own planet.",
    story: "Madagascar is not a side trip. It is an eighth continent. We keep the week honest: the highlands, the forest, then Nosy Be for the water.",
    highlights: ["Andasibe night walk", "Indri call at dawn", "Nosy Be snorkel", "Tana craft morning"],
    inclusions: STAYS,
    itinerary: [
      { day: "01", title: "Antananarivo", text: "The red city. A hill, a market, rest." },
      { day: "02–04", title: "Andasibe", text: "Rainforest, lemurs, a night that belongs to insects." },
      { day: "05–07", title: "Nosy Be", text: "Perfume island. The Mozambique Channel as a last page." },
    ],
    bestTime: "April – November",
  },
  {
    id: "forts-and-palaces",
    title: "Realm of Forts and Palaces",
    country: "Rajasthan",
    locations: ["Jaipur", "Jodhpur", "Udaipur", "Jaisalmer"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 2,
    price: 95000,
    region: "India",
    theme: "Heritage",
    status: "Open",
    featured: true,
    image: U("photo-1477587458883-47145ed94245"),
    gallery: [U("photo-1524492412937-b28074a5d7da"), U("photo-1599661046827-dacff0c0f09a"), U("photo-1603262110263-fb0112e7cc33")],
    blurb: "Pink, blue, white, gold — Rajasthan as a sequence of palaces you actually sleep in.",
    story: "We stay in havelis and palace hotels that still have courtyards. The desert is a night, not a stunt. Udaipur is the close, because water is the surprise.",
    highlights: ["Amber at opening", "Mehrangarh private corridor", "Lake Pichola dusk", "Jaisalmer fort after dark"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Jaipur", text: "The pink city, a palace breakfast, a bazaar that is still a bazaar." },
      { day: "03–04", title: "Jodhpur", text: "The blue city under a fort that is a mountain." },
      { day: "05", title: "Jaisalmer", text: "Sandstone, a dune, stars." },
      { day: "06–08", title: "Udaipur", text: "Lakes, a last palace, marble and water." },
    ],
    bestTime: "October – March",
  },
  {
    id: "backwater-spices",
    title: "Land of Backwaters & Spices",
    country: "Kerala",
    locations: ["Kochi", "Munnar", "Alleppey", "Kovalam"],
    duration: "6 Days · 5 Nights",
    days: 6,
    nights: 5,
    pax: 2,
    price: 78000,
    region: "India",
    theme: "Wellness",
    status: "Open",
    image: U("photo-1602216056096-3b40cc0c9944"),
    gallery: [U("photo-1593693397690-362cb9666fc2"), U("photo-1582510003544-4d00b7f74220"), U("photo-1507525428034-b723cf961d3e")],
    blurb: "Tea, houseboats, and an Ayurvedic quiet that the coast invented.",
    story: "Kerala is water and spice. A night on a houseboat that is not a party. A hill station that still smells of tea. A last Ayurvedic afternoon by the Arabian Sea.",
    highlights: ["Fort Kochi at blue hour", "Munnar tea walk", "Private houseboat night", "Ayurvedic consultation"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Kochi", text: "Chinese nets, a synagogue, a courtyard hotel." },
      { day: "03", title: "Munnar", text: "Tea as a landscape." },
      { day: "04–06", title: "Backwaters & the coast", text: "The kettuvallam, then Kovalam’s last swim." },
    ],
    bestTime: "November – February",
  },
  {
    id: "teerth-nagri",
    title: "Teerth Nagri",
    country: "Rishikesh",
    locations: ["Rishikesh"],
    duration: "5 Days · 4 Nights",
    days: 5,
    nights: 4,
    pax: 2,
    price: 52000,
    region: "India",
    theme: "Wellness",
    status: "Open",
    image: U("photo-1544735716-392fe2489ffa"),
    gallery: [U("photo-1582510003544-4d00b7f74220"), U("photo-1506905925346-21bda4d32df4"), U("photo-1545389336-cf090694435e")],
    blurb: "The Ganga as a teacher. Yoga that is not a brand. A town that still rings a bell at dusk.",
    story: "Rishikesh is a pilgrimage even if you do not call it one. We stay above the river, not in the noise. Dawn on the water. Evenings that end early on purpose.",
    highlights: ["Private Ganga aarti from a boat", "Sunrise yoga with a serious teacher", "Beatles ashram as a ruin, not a selfie", "Forest walk above the river"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Arrival & the river", text: "Settle. The Ganga does the rest." },
      { day: "03–04", title: "Practice", text: "Yoga, silence, a walk that is not a trek." },
      { day: "05", title: "Leave slowly", text: "One last dip, or not. The train or the car waits." },
    ],
    bestTime: "October – March",
  },
  {
    id: "mediterranean-majesty",
    title: "Mediterranean Majesty",
    country: "Italy & Monaco",
    locations: ["Rome", "Florence", "Amalfi", "Monaco"],
    duration: "10 Days · 9 Nights",
    days: 10,
    nights: 9,
    pax: 2,
    price: 295000,
    region: "Europe",
    theme: "Heritage",
    status: "Open",
    image: U("photo-1523906834658-6e24ef2386f9"),
    gallery: [U("photo-1516483638261-f4dbaf036963"), U("photo-1531572753322-ad063cecc140"), U("photo-1516483638261-f4dbaf036963")],
    blurb: "Italy’s long table, then a principality that faces the sea like a jewel box.",
    story: "Rome for stone, Florence for paint, the Amalfi for the cliff, Monaco for a night that still dresses. Ten days so none of it is a dash.",
    highlights: ["Vatican private corridor window", "Florence after the galleries close", "Amalfi boat to a cove", "Monaco harbour dusk"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–03", title: "Rome", text: "The eternal, at a human hour." },
      { day: "04–05", title: "Florence", text: "A city the size of a thought. Art, then a steak." },
      { day: "06–08", title: "Amalfi", text: "Cliffs, lemons, a terrace that faces nowhere else." },
      { day: "09–10", title: "Monaco", text: "A last principality. The sea, a square, a close." },
    ],
    bestTime: "April – June, September – October",
  },
  {
    id: "cherry-blossom-country",
    title: "Cherry Blossom Country",
    country: "Japan",
    locations: ["Tokyo", "Kyoto", "Osaka"],
    duration: "10 Days · 9 Nights",
    days: 10,
    nights: 9,
    pax: 2,
    price: 275000,
    region: "Asia",
    theme: "Culture",
    status: "Seasonal",
    featured: true,
    image: U("photo-1493976040374-85c8e12f0c0e"),
    gallery: [U("photo-1522383225653-ed111181a951"), U("photo-1545569341-9eb8b30979d9"), U("photo-1480796927426-f609979314bd")],
    blurb: "A country that invented attention. Temples, trains, and a season that lasts a week.",
    story: "Japan rewards those who do not hurry. We time the blossom if the year allows, and the foliage if it does not. A ryokan that still serves kaiseki as a ceremony.",
    highlights: ["Tsukiji inner tasting", "Kyoto tea with a master", "Arashiyama at opening", "Osaka night as a kitchen"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–04", title: "Tokyo", text: "Neighbourhoods, a sushi counter, neon as a material." },
      { day: "05–08", title: "Kyoto", text: "Temples in sequence. A ryokan. Moss and water." },
      { day: "09–10", title: "Osaka", text: "Appetite as culture. A last train, a last bowl." },
    ],
    bestTime: "March – April, October – November",
  },
  {
    id: "coffee-capital",
    title: "Coffee Capital",
    country: "Coorg",
    locations: ["Madikeri", "Kakkabe"],
    duration: "4 Days · 3 Nights",
    days: 4,
    nights: 3,
    pax: 2,
    price: 50000,
    region: "India",
    theme: "Wellness",
    status: "Open",
    image: U("photo-1447933601403-0c6688de566e"),
    gallery: [U("photo-1442512595331-e89e73853f31"), U("photo-1506905925346-21bda4d32df4"), U("photo-1544735716-392fe2489ffa")],
    blurb: "Mist, estates, and a cup that still has a farm attached to it.",
    story: "Coorg is a long weekend done properly. A planter’s bungalow. A walk through coffee that is still growing. Rain as a feature, not a flaw.",
    highlights: ["Estate walk with a planter", "Abbey Falls without the crowd", "Kodava kitchen supper", "Mist morning on the verandah"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Madikeri", text: "The hill town, a fort, a first fire in the evening." },
      { day: "03–04", title: "The estate", text: "Coffee, cardamom, a last slow breakfast." },
    ],
    bestTime: "October – March",
  },
  {
    id: "valley-of-serenity",
    title: "Valley of Serenity",
    country: "Kashmir",
    locations: ["Srinagar", "Gulmarg", "Pahalgam"],
    duration: "6 Days · 5 Nights",
    days: 6,
    nights: 5,
    pax: 2,
    price: 75000,
    region: "India",
    theme: "Mountains",
    status: "Open",
    image: U("photo-1595815771614-ade9d652a65d"),
    gallery: [U("photo-1626621341517-bbf3d9990a23"), U("photo-1506905925346-21bda4d32df4"), U("photo-1464822759023-fed622ff2c3b")],
    blurb: "A lake with a house on it, meadows, and a valley that still knows how to be quiet.",
    story: "Kashmir is a valley, not a slogan. A houseboat that is actually still. Gulmarg for the height. Pahalgam for the river. We keep the days uncrowded.",
    highlights: ["Dal Lake private shikara dawn", "Houseboat night on Nigeen", "Gulmarg meadow hour", "Pahalgam river walk"],
    inclusions: STAYS,
    itinerary: [
      { day: "01–02", title: "Srinagar", text: "The lake, the Mughal gardens, a houseboat that is a home." },
      { day: "03–04", title: "Gulmarg", text: "Meadows, a gondola if the sky is clear." },
      { day: "05–06", title: "Pahalgam", text: "The Lidder. Pine. A last night in the valley." },
    ],
    bestTime: "April – June, September – October",
  },
];

LOOP.collections = [
  {
    id: "sanatan",
    name: "Sanatan",
    devanagari: "सनातन",
    rasa: "Śānta",
    href: "sanatan.html",
    kicker: "The oldest way we leave home",
    promise: "You are not a tourist in your own civilisation.",
    lede: "Teerth is a sequence, not a checklist. We time the river, the door, and the hour. You bring the reason. We keep the rest from becoming tourism.",
    forWhom: "Those who want darshan without a queue as the memory. Families completing a vow. Anyone who still believes a city can change you.",
    notFor: "Temple-hopping. Photography as a sport. A schedule that treats aarti as content.",
    ritual: [
      "Darshan windows held before the public hour",
      "A scholar, not a script, walking with you",
      "Evenings that end when the bell ends them",
    ],
    pigment: "#3a221c",
    glyph: "स",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1800&q=80",
  },
  {
    id: "biker",
    name: "Biker",
    devanagari: "पथ",
    rasa: "Vīra",
    href: "biker.html",
    kicker: "The machine is not a prop",
    promise: "The road is the itinerary.",
    lede: "A motorcycle, a captain, a vehicle behind you with a mechanic. Himalaya, desert, or ghats. You ride. We keep the machine and the bed honest.",
    forWhom: "Riders who want the pass more than the postcard. Friends who already trust each other on gravel.",
    notFor: "A sightseeing coach with helmets. Anyone who wants the Himalaya from a window.",
    ritual: [
      "A road captain who has ridden the pass in weather",
      "A mechanic in the vehicle that follows",
      "Beds that expect dust, and dinners that expect hunger",
    ],
    pigment: "#16181d",
    glyph: "प",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1800&q=80",
  },
  {
    id: "community",
    name: "Community",
    devanagari: "संग",
    rasa: "Sakhya",
    href: "community.html",
    kicker: "For solo travellers — and people who want a table",
    glyph: "म",
    promise: "Arrive alone. Eat with a circle that already belongs.",
    lede: "Small hosted circles across India — Coorg estates, Kutch villages, Meghalaya kitchens. Never more than ten chairs. Solo travellers are welcome by design: one seat at a real table, a host who lives there, evenings that are not lonely. Friends can join the same circle. You book for the company, not a coach.",
    forWhom: "Solo travellers who want company without a group tour. Friends who want structure without itinerary theatre. Anyone who books for the table, the kitchen, and a place that still feels like a place.",
    notFor: "Coach groups. Influencer trips. A party that happens to be in Coorg. Anyone who needs fifty new Instagram friends.",
    ritual: [
      "Never more than ten chairs — solo seats held on purpose",
      "A host who lives there, not a guide who visits",
      "One long table every night that matters; mornings left unhurried",
      "From ₹50,000 / person — reshape the week to your budget",
    ],
    pigment: "#2a2318",
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1800&q=80",
  },
  {
    id: "solo",
    name: "Solo",
    href: "solo.html",
    kicker: "Built for one",
    promise: "The itinerary is built for one.",
    lede: "Rooms that do not punish a single traveller. Tables that do not stare at an empty chair. A designer who knows you are not waiting for anyone.",
    forWhom: "People who want India without a plus-one, a group chat, or a twin-share compromise.",
    notFor: "Couples looking for a deal. Anyone who wants the social of a group.",
    ritual: [
      "Single occupancy is the default, not a supplement surprise",
      "A pace that does not wait for a partner",
      "Evenings that can be quiet without being lonely",
    ],
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1800&q=80",
  },
  {
    id: "surprise",
    name: "Surprise",
    devanagari: "रहस्य",
    rasa: "Adbhuta",
    href: "surprise.html",
    kicker: "The envelope is the itinerary",
    promise: "The last luxury is not knowing.",
    lede: "Month, length, rooms — yes. Place — no. Forty-eight hours before you fly, the envelope opens. Decision fatigue ends at the booking.",
    forWhom: "People who are tired of thirty tabs. Couples who trust each other more than they trust a review. Anyone who wants to be a guest again.",
    notFor: "Planners who need the restaurant name in advance. Anyone whose visa names the city.",
    ritual: [
      "You choose the month, the length, and the rooms",
      "We choose the place",
      "The envelope opens forty-eight hours before you fly",
    ],
    pigment: "#141210",
    glyph: "र",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1800&q=80",
  },
  {
    id: "group",
    name: "Group",
    devanagari: "गण",
    rasa: "Utsaha",
    href: "group.html",
    kicker: "The house is held for you",
    promise: "One person books. Everyone else just arrives.",
    lede: "Eight to twenty-four chairs. A haveli, a ridge, a long table. Birthdays, companies, families, the friends who never manage to pick a date. We hold the house. You hold the people.",
    forWhom: "The one friend who always organises. Families who want one invoice. Companies done with a ballroom in Bengaluru.",
    notFor: "A discount for booking together. A tour with fifty strangers.",
    ritual: [
      "A private house, not a hotel floor",
      "One organiser, one invoice, one designer",
      "The rest of the group only has to arrive",
    ],
    pigment: "#1a2422",
    glyph: "ग",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1800&q=80",
  },
];

LOOP.world = {
  id: "world",
  name: "World",
  devanagari: "विश्व",
  href: "journeys.html?collection=world",
  pigment: "#1c1916",
  glyph: "व",
  promise: "Put a finger on the map. We will take you there.",
};

LOOP.houseJourneys = [
  {
    id: "kashi-antarah",
    title: "Kashi Antarātmā",
    country: "Varanasi",
    locations: ["Assi", "Manikarnika", "Sarnath"],
    duration: "6 Days · 5 Nights",
    days: 6,
    nights: 5,
    pax: 2,
    price: 89000,
    currency: "INR",
    region: "India",
    theme: "Sanatan",
    collection: "sanatan",
    status: "Open",
    featured: true,
    blurb: "The river as a teacher. Six days on the ghats, timed to light, not to a list.",
    story: "Kashi is not a city you see. It is a city that sees you. We stay on the river, rise for the first light, and leave the rest of the day unhurried. Darshan is arranged. Photography is not the point. A scholar of the city walks with you — not a script.",
    highlights: ["Private boat at first light, before the river fills", "Aarti from the water, not from a stand", "Sarnath at opening, then silence", "A table that understands sattvic without performing it"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–02", title: "Arrive and sit", text: "The ghat you will return to. No programme until evening. The city introduces itself." },
      { day: "03–04", title: "The river", text: "Dawn on the water. Lanes that still belong to the people who live in them. Manikarnika at a respectful hour." },
      { day: "05–06", title: "Sarnath, then leave slowly", text: "The deer park, a last lamp, a train or a flight that does not steal the morning." },
    ],
    bestTime: "October – March",
  },
  {
    id: "char-dham-path",
    title: "Char Dham Path",
    country: "Uttarakhand",
    locations: ["Yamunotri", "Gangotri", "Kedarnath", "Badrinath"],
    duration: "12 Days · 11 Nights",
    days: 12,
    nights: 11,
    pax: 2,
    price: 99000,
    currency: "INR",
    region: "India",
    theme: "Sanatan",
    collection: "sanatan",
    status: "Seasonal",
    blurb: "Four abodes. One procession. Helicopters where the mountain asks for them, walking where it should be walked.",
    story: "The Char Dham is a vow with logistics attached. We do not make it a race. Yamunotri and Gangotri at a human pace. Kedarnath with the respect the climb deserves. Badrinath as a close, not a tick. Stays are clean, warm, and close to the door.",
    highlights: ["Helicopter where the mountain is kinder that way", "Kedarnath darshan before the crowd", "Gangotri at the hour the river is still a voice", "A priest who speaks, not recites"],
    inclusions: STAYS_IN.concat(["Helicopter legs as named", "All yatra registrations and inner-line work"]),
    itinerary: [
      { day: "01–03", title: "Yamunotri", text: "The first dham. Steam, stone, a night that ends early." },
      { day: "04–06", title: "Gangotri", text: "The river at its youngest. A temple that faces the source." },
      { day: "07–09", title: "Kedarnath", text: "The climb, or the air. Darshan, then a night the mountain keeps quiet." },
      { day: "10–12", title: "Badrinath", text: "The close. Alaknanda light. A last prasad, then down." },
    ],
    bestTime: "May – June, September – October",
  },
  {
    id: "two-shores",
    title: "Two Shores",
    country: "Dwarka & Rameswaram",
    locations: ["Dwarka", "Rameswaram"],
    duration: "10 Days · 9 Nights",
    days: 10,
    nights: 9,
    pax: 2,
    price: 95000,
    currency: "INR",
    region: "India",
    theme: "Sanatan",
    collection: "sanatan",
    status: "Open",
    blurb: "West sea, east sea. Krishna’s city and Rama’s bridge — the subcontinent held between two lamps.",
    story: "India is a land with two holy shores. We give each its days. Dwarka for the west, the bet, the wind. Rameswaram for the east, the corridor, the bath. A flight between them so the week is not a train of fatigue.",
    highlights: ["Bet Dwarka at a working hour", "Rameswaram corridor before the buses", "A snan that is a rite, not a photo", "Evenings that belong to the sea"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–05", title: "Dwarka", text: "The western lamp. The old city, the bet, a sunset that is still a prayer." },
      { day: "06–10", title: "Rameswaram", text: "The eastern lamp. The corridor, the twenty-two wells, a last look at the bridge of stones." },
    ],
    bestTime: "November – March",
  },
  {
    id: "mahakal-dawn",
    title: "Mahakal Dawn",
    country: "Ujjain",
    locations: ["Ujjain"],
    duration: "5 Days · 4 Nights",
    days: 5,
    nights: 4,
    pax: 2,
    price: 68000,
    currency: "INR",
    region: "India",
    theme: "Sanatan",
    collection: "sanatan",
    status: "Open",
    blurb: "One jyotirlinga. Enough time. The Shipra, and a city that still keeps a clock older than the station.",
    story: "Ujjain is not a stop between somewhere. Five days so Mahakaleshwar is a relationship, not a queue. Bhasma aarti is arranged with dignity. The rest of the day is the ghats, the observatory, a table that does not hurry.",
    highlights: ["Bhasma aarti held without the scramble", "Shipra at first light", "Vedh Shala when the sky is actually readable", "A quiet house near the river"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–02", title: "Arrive", text: "The river first. The temple when you are ready, not when the car is." },
      { day: "03–04", title: "The hour", text: "Bhasma aarti. Then a day that is allowed to be empty." },
      { day: "05", title: "Leave", text: "One last lamp. The train does not take the morning." },
    ],
    bestTime: "October – March",
  },
  {
    id: "high-road-leh",
    title: "High Road to Leh",
    country: "Ladakh",
    locations: ["Manali", "Jispa", "Sarchu", "Leh"],
    duration: "11 Days · 10 Nights",
    days: 11,
    nights: 10,
    pax: 2,
    price: 98000,
    currency: "INR",
    region: "India",
    theme: "Biker",
    collection: "biker",
    status: "Seasonal",
    featured: true,
    blurb: "Manali to Leh on a machine that belongs on this road. A captain, a mechanic, and passes that still deserve respect.",
    story: "This is the road people mean when they say they want to ride India. We do not hurry the altitude. We do not pretend the gravel is a story you tell later. A support vehicle carries what the bike should not. You ride. The mountain decides the pace.",
    highlights: ["A serviced motorcycle fitted to you", "Baralacha and Tanglang with a captain who has crashed so you don’t", "Nights in Jispa and Sarchu that expect cold", "Two days in Leh that are not a victory lap"],
    inclusions: STAYS_BIKE,
    itinerary: [
      { day: "01–02", title: "Manali", text: "The machine, the fit, a first ride that is not the pass." },
      { day: "03–07", title: "The high road", text: "Jispa, Sarchu, the long valley. Altitude as a teacher." },
      { day: "08–11", title: "Leh", text: "Rest, a monastery hour, a last loop if the body agrees." },
    ],
    bestTime: "June – September",
  },
  {
    id: "spiti-circuit",
    title: "Spiti Circuit",
    country: "Spiti",
    locations: ["Shimla", "Nako", "Kaza", "Chandratal"],
    duration: "10 Days · 9 Nights",
    days: 10,
    nights: 9,
    pax: 2,
    price: 92000,
    currency: "INR",
    region: "India",
    theme: "Biker",
    collection: "biker",
    status: "Seasonal",
    blurb: "A colder, quieter Himalaya. Fossil villages, a monastery on a crag, and a lake that is earned.",
    story: "Spiti is not Ladakh’s understudy. It is a different silence. We ride the Kinnaur side in, the Chandra side out if the road is open. Kaza is a pause, not a party. Chandratal is a morning, not a parking lot.",
    highlights: ["Nako lake at dusk", "Kye and Dhankar without a convoy", "Chandratal if the road allows", "A mechanic who has rebuilt a carburettor at 3,800 metres"],
    inclusions: STAYS_BIKE,
    itinerary: [
      { day: "01–02", title: "Shimla to Kinnaur", text: "The orchard road, then the gorge." },
      { day: "03–07", title: "Spiti", text: "Nako, Tabo, Kaza. Villages that still keep a fossil clock." },
      { day: "08–10", title: "The lake, then down", text: "Chandratal if the mountain agrees. Then the long descent." },
    ],
    bestTime: "June – September",
  },
  {
    id: "ghats-monsoon",
    title: "Ghats in the Rain",
    country: "Western Ghats",
    locations: ["Mulshi", "Mahabaleshwar", "Amboli"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 2,
    price: 78000,
    currency: "INR",
    region: "India",
    theme: "Biker",
    collection: "biker",
    status: "Seasonal",
    blurb: "The ghats when they are themselves — wet, green, and empty of the weekend.",
    story: "Most people ride the ghats in December. We wait for the rain. The road is slower. The forest is the point. Stays with a fire and a floor that can take a dripping jacket. This is not a Himalayan story. It is a Konkan one.",
    highlights: ["Ghat roads without the Sunday race", "A bungalow that expects monsoon", "Amboli when the waterfall is a wall", "Evenings that end with soup, not a playlist"],
    inclusions: STAYS_BIKE,
    itinerary: [
      { day: "01–03", title: "Mulshi", text: "The first ghats. Lake, mist, a machine breaking in." },
      { day: "04–06", title: "Mahabaleshwar & the spine", text: "Old ghat roads, a table with strawberries if the season still has them." },
      { day: "07–08", title: "Amboli", text: "The wettest pause. Then home before the highway." },
    ],
    bestTime: "July – September",
  },
  {
    id: "thar-iron",
    title: "Thar Iron",
    country: "Rajasthan",
    locations: ["Jodhpur", "Osian", "Jaisalmer"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 82000,
    currency: "INR",
    region: "India",
    theme: "Biker",
    collection: "biker",
    status: "Open",
    blurb: "Desert as a surface. Forts as punctuation. A night where the road ends and the sand begins.",
    story: "The Thar is a riding surface people underestimate. Straight, then not. We start under Mehrangarh, cut through Osian, and finish in Jaisalmer when the fort is a silhouette. One night off the tar, on purpose.",
    highlights: ["Dawn under Mehrangarh", "Osian empty of coaches", "A dune night that is a camp, not a package", "Jaisalmer after the day-trippers"],
    inclusions: STAYS_BIKE,
    itinerary: [
      { day: "01–02", title: "Jodhpur", text: "The blue city as a garage and a first ride." },
      { day: "03–04", title: "The desert road", text: "Osian, then the long straight toward gold stone." },
      { day: "05–07", title: "Jaisalmer", text: "The fort, a last loop, sand in the chain as a souvenir." },
    ],
    bestTime: "November – February",
  },
  {
    id: "coorg-table",
    title: "The Coorg Table",
    country: "Coorg",
    locations: ["Kakkabe", "Madikeri"],
    duration: "5 Days · 4 Nights",
    days: 5,
    nights: 4,
    pax: 8,
    maxPax: 10,
    seats: 3,
    price: 72000,
    currency: "INR",
    region: "India",
    theme: "Community",
    collection: "community",
    status: "Limited",
    blurb: "Ten chairs on an estate. A Kodava kitchen. Mist as a houseguest.",
    story: "A planter’s bungalow, a cook who still argues about pork, and eight to ten people who booked because they wanted a table more than a viewpoint. Walks through coffee in the morning. The same chairs at night. No itinerary after lunch.",
    highlights: ["One estate, five days, no hotel hopping", "Kodava supper that is a house, not a resort night", "A walk with a planter, not a naturalist on contract", "Never more than ten"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01", title: "Arrive to the table", text: "The bungalow. Names. A first fire." },
      { day: "02–04", title: "The estate", text: "Coffee, a walk, a long lunch, rain if it comes." },
      { day: "05", title: "Leave after breakfast", text: "The table again. Then the ghats down." },
    ],
    bestTime: "October – March",
  },
  {
    id: "kutch-circle",
    title: "Kutch Circle",
    country: "Kutch",
    locations: ["Bhuj", "Hodka", "Rann"],
    duration: "6 Days · 5 Nights",
    days: 6,
    nights: 5,
    pax: 8,
    maxPax: 10,
    seats: 5,
    price: 85000,
    currency: "INR",
    region: "India",
    theme: "Community",
    collection: "community",
    status: "Seasonal",
    featured: true,
    blurb: "Makers, salt, and a white desert that is a floor. A circle of ten, hosted.",
    story: "Kutch is a district of hands. We stay with a host who knows which village still dyes with indigo and which has become a showroom. The Rann is one evening, not the product. The table is the product.",
    highlights: ["Ajrakh and silver with the family that makes them", "Hodka as a village, not a venue", "The Rann at the hour it goes from salt to mercury", "Ten chairs, one cook"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–02", title: "Bhuj", text: "The bazaar with someone who still shops there." },
      { day: "03–05", title: "Hodka & the Rann", text: "Craft in the morning, salt at dusk, the same table at night." },
      { day: "06", title: "Out", text: "A last cup. The airport at Bhuj." },
    ],
    bestTime: "November – February",
  },
  {
    id: "meghalaya-kitchen",
    title: "Meghalaya Kitchen",
    country: "Meghalaya",
    locations: ["Shillong", "Mawlynnong", "Dawki"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 8,
    maxPax: 10,
    seats: 4,
    price: 95000,
    currency: "INR",
    region: "India",
    theme: "Community",
    collection: "community",
    status: "Open",
    blurb: "Khasi tables, living bridges, a river you can see through. A small circle in the wet hills.",
    story: "Meghalaya is too often a waterfall list. We go for the kitchen and the rain. A homestay that is a home. Living roots as a walk, not a ticket. Dawki when the water is a lens. Eight people who wanted the northeast without a convoy.",
    highlights: ["A Khasi kitchen that is not a tasting menu", "Living bridge at an hour without a queue", "Dawki when the boats are few", "Shillong jazz as a night, not a brand"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–03", title: "Shillong", text: "The ridge, a market, a table that takes time." },
      { day: "04–06", title: "The villages", text: "Mawlynnong, a bridge that is still growing, rain as a feature." },
      { day: "07–08", title: "Dawki, then out", text: "The river. A last slow drive. Guwahati when you are ready." },
    ],
    bestTime: "October – April",
  },
  {
    id: "solo-hills",
    title: "One in the Hills",
    country: "Himachal",
    locations: ["Jibhi", "Tirthan", "Shoja"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 1,
    price: 78000,
    currency: "INR",
    region: "India",
    theme: "Solo",
    collection: "solo",
    status: "Open",
    featured: true,
    blurb: "A week in the Tirthan valley, built for one. Walks, a river, rooms that do not charge you for arriving alone.",
    story: "Solo in the Himalaya is not a sad table. It is a pace nobody else has to agree to. We keep you in small houses above the Tirthan, with a driver who does not fill the silence, and evenings that can be a book or a local table — your call, every day.",
    highlights: ["Single occupancy as the default", "Tirthan walks without a group flag", "A riverside stay that is not a hostel bunk", "A designer on call who understands one suitcase"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–02", title: "Arrive", text: "Delhi or Chandigarh, then the valley. No welcome circle. A room that is yours." },
      { day: "03–05", title: "The river", text: "Walks, a village, a day that can stay empty." },
      { day: "06–07", title: "Shoja, then out", text: "Higher air, then the road down on your own clock." },
    ],
    bestTime: "March – June, September – November",
  },
  {
    id: "solo-malabar",
    title: "Malabar Alone",
    country: "Kerala",
    locations: ["Fort Kochi", "Alleppey", "Varkala"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 1,
    price: 82000,
    currency: "INR",
    region: "India",
    theme: "Solo",
    collection: "solo",
    status: "Open",
    blurb: "Kochi, a houseboat for one, and a cliff over the Arabian Sea. Kerala without a twin-share compromise.",
    story: "Kerala is often sold as a couple’s product. This one is not. A courtyard in Fort Kochi. A kettuvallam that does not put a stranger in the other bed. Varkala when you want the sea. Ayurveda if you want it — not because a brochure assumed a pair.",
    highlights: ["Houseboat night without a forced companion", "Fort Kochi at a walking pace", "Varkala cliff at your own hour", "An Ayurvedic consult that is for your body, not a package of two"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–03", title: "Fort Kochi", text: "Lanes, a synagogue, a café that will let you sit with a book." },
      { day: "04–05", title: "The backwaters", text: "A boat that is yours. The lake does the talking." },
      { day: "06–08", title: "Varkala", text: "The cliff, the water, a last slow breakfast." },
    ],
    bestTime: "November – March",
  },
  {
    id: "solo-gokarna",
    title: "Gokarna Quiet",
    country: "Karnataka",
    locations: ["Gokarna", "Hampi"],
    duration: "6 Days · 5 Nights",
    days: 6,
    nights: 5,
    pax: 1,
    price: 62000,
    currency: "INR",
    region: "India",
    theme: "Solo",
    collection: "solo",
    status: "Open",
    blurb: "A temple town, a beach that is still a beach, then the boulders of Hampi. For one.",
    story: "Gokarna still allows a solo traveller to disappear in the right way. A small stay near the water. Om Beach without a party brief. Then Hampi, where stone is company enough. We do not put you in a dorm to make the price look kind.",
    highlights: ["A room of your own near the water", "Beaches at hours without a crowd", "Hampi at opening, on foot", "Trains and cars timed so you are never stranded at dusk"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–03", title: "Gokarna", text: "The temple town, a beach, evenings that end when you want." },
      { day: "04–06", title: "Hampi", text: "Boulders, a river, a last sunrise on the hill." },
    ],
    bestTime: "October – March",
  },
  {
    id: "sealed-seven",
    title: "The Sealed Seven",
    country: "India",
    locations: ["Revealed 48 hours before you fly"],
    duration: "7 Days · 6 Nights",
    days: 7,
    nights: 6,
    pax: 2,
    price: 88000,
    currency: "INR",
    region: "India",
    theme: "Surprise",
    collection: "surprise",
    status: "Open",
    featured: true,
    sealed: true,
    blurb: "Seven days. A place you will not know until two days before. The rooms will be right. That is the product.",
    story: "You tell us the month and how you like to sleep. We tell you nothing else. Forty-eight hours before departure, an envelope: city, packing line, the first address. India has enough rooms that this is not a gimmick. It is an edit.",
    highlights: ["Destination held until 48 hours before", "Rooms at the Prestige standard or above", "A designer who already knows what you will not like", "No reviews to read, on purpose"],
    inclusions: STAYS_IN.concat(["The envelope, on time"]),
    itinerary: [
      { day: "01", title: "You fly", text: "Someone meets you. The place begins." },
      { day: "02–06", title: "The week", text: "Enough structure. Not enough to feel like a tour. You will not need a queue." },
      { day: "07", title: "You know it well enough to miss it", text: "Home. The envelope was the souvenir." },
    ],
    bestTime: "Year-round",
  },
  {
    id: "sealed-weekend",
    title: "The Sealed Weekend",
    country: "India",
    locations: ["Revealed 48 hours before you fly"],
    duration: "4 Days · 3 Nights",
    days: 4,
    nights: 3,
    pax: 2,
    price: 55000,
    currency: "INR",
    region: "India",
    theme: "Surprise",
    collection: "surprise",
    status: "Open",
    sealed: true,
    blurb: "A long weekend you cannot over-plan. Leave Friday. Know Thursday.",
    story: "For the Bengaluru and Mumbai desks that cannot take seven days and will ruin four if they are allowed to. A sealed weekend. Train or short hop. A house that is not a hotel you have already seen on a reel.",
    highlights: ["Thursday night: the place", "Friday: you leave", "Monday: you are back at the desk", "No group, no coach, no itinerary PDF in advance"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01", title: "Leave", text: "The envelope was yesterday. Today is a platform or a gate." },
      { day: "02–03", title: "The pause", text: "A place at the right distance from your city." },
      { day: "04", title: "Return", text: "The office will still be there." },
    ],
    bestTime: "Year-round",
  },
  {
    id: "sealed-two",
    title: "Sealed, for two",
    country: "India",
    locations: ["Revealed 48 hours before you fly"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 2,
    price: 98000,
    currency: "INR",
    region: "India",
    theme: "Surprise",
    collection: "surprise",
    status: "Limited",
    sealed: true,
    blurb: "An anniversary that cannot be Googled. Eight days, two people, one envelope.",
    story: "Honeymoons and anniversaries fail when they become a moodboard. This one cannot. We know the month, the diet, the pace. You know nothing else. The rooms will have a door that closes. The table will be for two.",
    highlights: ["Built only for two", "No shared tables, no group legs", "A packing list that does not leak the place", "One private supper that is the point of a night"],
    inclusions: STAYS_IN,
    itinerary: [
      { day: "01–02", title: "Arrive as guests", text: "Not as planners. That was our work." },
      { day: "03–07", title: "The week you did not design", text: "Land or water — you told us which. Not where." },
      { day: "08", title: "Leave", text: "You may tell people after. Not before." },
    ],
    bestTime: "Year-round",
  },
  {
    id: "haveli-family",
    title: "A Haveli, Held",
    country: "Rajasthan",
    locations: ["A private haveli in Rajasthan"],
    duration: "8 Days · 7 Nights",
    days: 8,
    nights: 7,
    pax: 8,
    minPax: 8,
    maxPax: 18,
    price: 89000,
    currency: "INR",
    region: "India",
    theme: "Group",
    collection: "group",
    status: "Open",
    featured: true,
    blurb: "The whole house. Eight to eighteen people. One invoice. Grandparents and children under the same courtyard.",
    story: "Family trips die in hotel corridors. We take a haveli and give it to you. A cook who can feed eighteen without a buffet. A courtyard that holds a birthday and a nap. Day trips for those who want them. The house for those who do not.",
    highlights: ["The haveli is yours — not a floor of a hotel", "One organiser, one designer, one bill", "A cook who takes instruction from the eldest if that is the culture", "Rooms that split three generations without a fight"],
    inclusions: STAYS_IN.concat(["The house exclusively", "A host manager on the grounds"]),
    itinerary: [
      { day: "01", title: "The house opens", text: "Everyone arrives. The courtyard does the rest." },
      { day: "02–07", title: "As you are", text: "A fort for those who want it. A verandah for those who do not. Supper at one table." },
      { day: "08", title: "The house closes", text: "You leave together, which was the difficult part, already done." },
    ],
    bestTime: "October – March",
  },
  {
    id: "friends-of-the-house",
    title: "Friends of the House",
    country: "Goa & the Konkan",
    locations: ["A private house on the Konkan"],
    duration: "6 Days · 5 Nights",
    days: 6,
    nights: 5,
    pax: 8,
    minPax: 8,
    maxPax: 16,
    price: 75000,
    currency: "INR",
    region: "India",
    theme: "Group",
    collection: "group",
    status: "Open",
    blurb: "The college group, the wedding side, the friends who never pick a date. A house, a cook, a week.",
    story: "Someone has to book. That someone is tired. We take a house on the water that is not a villa from a reel: enough rooms, a cook, a table that survives a late night. No club. No itinerary that requires a WhatsApp poll.",
    highlights: ["A house that sleeps sixteen without bunk-bed politics", "A cook, a stocked kitchen, no restaurant votes", "The sea as an option, not a schedule", "One person deals with us. Everyone else just comes"],
    inclusions: STAYS_IN.concat(["The house exclusively"]),
    itinerary: [
      { day: "01", title: "Keys", text: "The organiser arrives first if they want. Or with the rest." },
      { day: "02–05", title: "The week", text: "Swim, sleep, a long lunch. A village if anyone is restless." },
      { day: "06", title: "Lock the door", text: "You will already be planning the next one. We can hold dates." },
    ],
    bestTime: "November – March",
  },
  {
    id: "company-ridge",
    title: "Company on the Ridge",
    country: "Himachal",
    locations: ["A ridge house above the deodars"],
    duration: "5 Days · 4 Nights",
    days: 5,
    nights: 4,
    pax: 10,
    minPax: 10,
    maxPax: 24,
    price: 82000,
    currency: "INR",
    region: "India",
    theme: "Group",
    collection: "group",
    status: "Open",
    blurb: "A company offsite that is not a ballroom. Ten to twenty-four. Pine, a long table, rooms that close.",
    story: "The Himalaya is a better whiteboard. We hold a ridge house: meeting if you must, walking if you are wise, a table that is not a buffet in a conference hotel. No team-building theatre. Air, beds, and a cook. The work will still happen. It will happen better.",
    highlights: ["A house, not a resort with a ‘breakout zone’", "Starlink if you insist, a cupboard for laptops if you are brave", "Rooms that allow a door to close", "One invoice to the company"],
    inclusions: STAYS_IN.concat(["The house exclusively", "A working room with a door"]),
    itinerary: [
      { day: "01", title: "Up", text: "Chandigarh or the airport, then the ridge. Phones still work. The view works harder." },
      { day: "02–04", title: "The work, or not", text: "Mornings for those who need a table. Afternoons for the forest. Evenings for the people you actually hired." },
      { day: "05", title: "Down", text: "You will have decided something. That was the point." },
    ],
    bestTime: "March – June, September – November",
  },
];

LOOP.journeys = LOOP.journeys.concat(LOOP.houseJourneys);
LOOP.journeys.forEach((j) => {
  if (!j.collection) j.collection = "world";
  if (!j.currency) j.currency = "INR";
  j.currency = "INR";
});

const HOUSE_SHOTS = {
  "kashi-antarah": ["photo-1582510003544-4d00b7f74220", "photo-1570168007204-dfb528c6958f", "photo-1524492412937-b28074a5d7da"],
  "char-dham-path": ["photo-1544735716-392fe2489ffa", "photo-1506905925346-21bda4d32df4", "photo-1464822759023-fed622ff2c3b"],
  "two-shores": ["photo-1507525428034-b723cf961d3e", "photo-1559827260-dc66d52bef19", "photo-1514282401047-d79a71a590e8"],
  "mahakal-dawn": ["photo-1524492412937-b28074a5d7da", "photo-1599661046827-dacff0c0f09a", "photo-1603262110263-fb0112e7cc33"],
  "high-road-leh": ["photo-1626621341517-bbf3d9990a23", "photo-1506905925346-21bda4d32df4", "photo-1581793745862-99fde7fa73d2"],
  "spiti-circuit": ["photo-1506905925346-21bda4d32df4", "photo-1464822759023-fed622ff2c3b", "photo-1544735716-392fe2489ffa"],
  "ghats-monsoon": ["photo-1447933601403-0c6688de566e", "photo-1602216056096-3b40cc0c9944", "photo-1442512595331-e89e73853f31"],
  "thar-iron": ["photo-1599661046827-dacff0c0f09a", "photo-1477587458883-47145ed94245", "photo-1603262110263-fb0112e7cc33"],
  "coorg-table": ["photo-1447933601403-0c6688de566e", "photo-1442512595331-e89e73853f31", "photo-1602216056096-3b40cc0c9944"],
  "kutch-circle": ["photo-1603262110263-fb0112e7cc33", "photo-1599661046827-dacff0c0f09a", "photo-1477587458883-47145ed94245"],
  "meghalaya-kitchen": ["photo-1544735716-392fe2489ffa", "photo-1506905925346-21bda4d32df4", "photo-1602216056096-3b40cc0c9944"],
  "solo-hills": ["photo-1506905925346-21bda4d32df4", "photo-1464822759023-fed622ff2c3b", "photo-1544735716-392fe2489ffa"],
  "solo-malabar": ["photo-1602216056096-3b40cc0c9944", "photo-1593693397690-362cb9666fc2", "photo-1507525428034-b723cf961d3e"],
  "solo-gokarna": ["photo-1507525428034-b723cf961d3e", "photo-1559827260-dc66d52bef19", "photo-1524492412937-b28074a5d7da"],
  "sealed-seven": ["photo-1467269204594-9661b134dd2b", "photo-1523906834658-6e24ef2386f9", "photo-1502602898657-3e91760cbb34"],
  "sealed-weekend": ["photo-1602216056096-3b40cc0c9944", "photo-1477587458883-47145ed94245", "photo-1507525428034-b723cf961d3e"],
  "sealed-two": ["photo-1514282401047-d79a71a590e8", "photo-1514282401047-d79a71a590e8", "photo-1555881400-74d7acaacd8b"],
  "haveli-family": ["photo-1477587458883-47145ed94245", "photo-1599661046827-dacff0c0f09a", "photo-1524492412937-b28074a5d7da"],
  "friends-of-the-house": ["photo-1507525428034-b723cf961d3e", "photo-1559827260-dc66d52bef19", "photo-1602216056096-3b40cc0c9944"],
  "company-ridge": ["photo-1464822759023-fed622ff2c3b", "photo-1506905925346-21bda4d32df4", "photo-1544735716-392fe2489ffa"],
};

LOOP.houseJourneys.forEach((j) => {
  const shots = HOUSE_SHOTS[j.id];
  if (shots) {
    j.image = U(shots[0]);
    j.gallery = shots.slice(1).map((id) => U(id));
  }
  // prices stay in INR
});

LOOP.exclusions = [
  "International flights to the start city, unless the trip page says otherwise",
  "Visas, travel insurance, and personal medical cover",
  "Meals not listed in the itinerary",
  "Personal shopping, spa, and hotel extras",
  "Tips, unless arranged in writing",
];

LOOP.suites = [
  { id: "classic", name: "Classic", note: "The trip as written — your from price.", add: 0 },
  { id: "prestige", name: "Prestige", note: "Suites and private tables. +22% on from price.", add: 0.22 },
  { id: "royal", name: "Royal", note: "Residences, not rooms. +45% on from price.", add: 0.45 },
];

LOOP.addons = [
  { id: "transfers", name: "Chauffeured upgrades throughout", price: 18000 },
  { id: "dinner", name: "A private farewell supper", price: 12000 },
  { id: "spa", name: "Spa or wellness afternoon", price: 8000 },
  { id: "photo", name: "A photographer for one day", price: 15000 },
];
